# This is a YAML-formatted file.  Declare variables to be passed into your templates.

externalPort: 443
externalProtocol: https
externalHost: acs.eksalfos.duckdns.org

persistence:
  enabled: true
  storageClass:
    enabled: true
    name: nfs-client

global:
  alfrescoRegistryPullSecrets: orealfos-registry-secrets
  elasticsearch:
    host: vpc-orealfos-dxb3me5op6elpubsx5gac3nqai.us-west-2.es.amazonaws.com
    port: 443
    protocol: https
    user: alfresco
    password: Alfr3sc@

repository:
  image:
    #repository: quay.io/alfresco/alfresco-content-repository-aws
    repository: 817632472177.dkr.ecr.us-west-2.amazonaws.com/orealfos/alfresco/alfresco-content-repository-aws-os
    tag: 7.2.1
  licenseSecret: acslicense
  environment:
    JAVA_OPTS: >-
      -Dtransform.service.enabled=true
      -XX:MinRAMPercentage=50
      -XX:MaxRAMPercentage=80
      -Dencryption.keystore.type=JCEKS
      -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
      -Dencryption.keyAlgorithm=DESede
      -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
      -Dmetadata-keystore.aliases=metadata
      -Dmetadata-keystore.metadata.algorithm=DESede
      -Dencryption.ssl.truststore.location=/usr/local/tomcat/truststore.pkcs12
      -Dencryption.ssl.truststore.type=PKCS12
      -Dssl-truststore.password=sph3re

s3connector:
  enabled: true
  config:
    bucketName: orealfos
    bucketLocation: us-west-2

pdfrenderer:
  image:
    tag: 2.5.7

imagemagick:
  image:
    tag: 2.5.7

libreoffice:
  image:
    tag: 2.5.7

tika:
  image:
    tag: 2.5.7

transformmisc:
  image:
    tag: 2.5.7

aiTransformer:
  image:
    tag: 1.4.2

filestore:
  image:
    tag: 0.16.1

alfresco-search:
  enabled: false
  searchServicesImage:
    tag: 2.0.4

alfresco-elasticsearch-connector:
  enabled: true
  reindexing:
    enabled: true
    postgresql:
      url: jdbc:postgresql://orealfos-cluster.cluster-cdwmz9iuh1uw.us-west-2.rds.amazonaws.com:5432/alfresco
alfresco-digital-workspace:
  image:
    repository: 817632472177.dkr.ecr.us-west-2.amazonaws.com/orealfos/alfresco/alfresco-digital-workspace
    tag: 2.9.0
    pullPolicy: IfNotPresent
share:
  image:
    tag: 7.2.1

postgresql:
  enabled: false
  image:
    tag: 13.3.0

postgresql-syncservice:
  enabled: false
  image:
    tag: 13.3.0

database:
  external: true
  driver: org.postgresql.Driver
  url: jdbc:postgresql://orealfos-cluster.cluster-cdwmz9iuh1uw.us-west-2.rds.amazonaws.com:5432/
  user: alfresco
  password: alfresco

activemq:
  enabled: false  

alfresco-sync-service:
  syncservice:
    image:
      tag: 3.7.3-A1
  messageBroker:
    url: ssl://b-ced50fbf-11ca-4c83-a995-9391526a5c58-1.mq.us-west-2.amazonaws.com:61617
    user: alfresco
    password: alfrescomess

messageBroker: &acs_messageBroker
  url: ssl://b-ced50fbf-11ca-4c83-a995-9391526a5c58-1.mq.us-west-2.amazonaws.com:61617
  user: alfresco
  password: alfrescomess
